### ISSUE TITLE
Terminate once handshake captured

### ISSUE THREAD

**Issue by Tommrodrigues** [cyrus-and/zizzania#10]
Hi there, thanks for making this excellent project! I'm currently trying to make a Python script which [integrates zizzania](https://github.com/Tommrodrigues/WiFiCrackPy/blob/master/WiFiCrackPy-DeAuth.py) for Wi-Fi cracking.

I would like to be able to utilise zizzania for the WPA handshake capturing part, then proceed with file conversion and cracking afterwards.

At the moment, however, I'm running into a bit of a problem:

```python
subprocess.run(['sudo', expanduser('~') + '/zizzania/src/zizzania', '-i', iface, '-b', bssid, '-w', 'capture.pcap'])
subprocess.run([expanduser('~') + '/hashcat-utils/src/cap2hccapx.bin', 'capture.pcap', 'capture.hccapx'], stderr=subprocess.PIPE)
```

Once called, zizzania does a great job capturing the handshake of the target network, but it requires `Ctrl-C` to exit. Doing so is problematic as it will terminate the Python script entirely.

Ideally, it'd be great if there were a flag we could add like `-k` which would terminate zizzania as soon as a full handshake is captured - do you think this is something that could be integrated?

Otherwise I think I'll probably be left having to make a bulky solution to read the output live and terminate the subprocess once `^_^ Full handshake` is detected.

Thanks in advance for your help!

P.S. Do you know from which year MacBook models are generally affected by the issue mentioned in #6 as I'd like to integrate a feature which would automatically disable packet injection on the affected models to prevent restarts? :)

**Comment by cyrus-and** [comment]
Hi! I wrote a similar script recently where I use zizzania for the same purpose. I didn't have that problem because I didn't want to run zizzania until an handshake is captured, as it might never happen for several reasons. Instead what I ended up doing is to keep a separate data store for the captured handshakes and each run of zizzania just executes (for each channel and BSSIDs that still need to be processed) for a limited amount of time, then is killed and started over with new parameters, and so on...

> P.S. Do you know from which year MacBook models are generally affected by the issue mentioned in #6 as I'd like to integrate a feature which would automatically disable packet injection on the affected models to prevent restarts? :)

I have a `MacBook Pro (Retina, 15-inch, Mid 2014)` and I don't have this issue, I think you can query the firmware or card type information, but I know nothing more what's already written on #6. But I wouldn't trust the captured packets though, even if I don't get a crash here, I still get corrupted packages.

**Comment by Tommrodrigues** [comment]
Thanks for getting back to me so quickly. That makes sense what you ended up doing i.e. running zizzania for a set period of time then restarting it. However, I'd still like to be able to run zizzania and leave it until a full handshake is captured and then terminate it.

Is this something that could be integrated into this project - simply a flag that would make the script terminate once a handshake is captured? Otherwise I will try to develop some code that screens the output and waits for a full handshake, and then does the termination.

Regarding the compatibility of MacBook models, I'll have a bit more of a deep dive online to see at which point packet injection becomes impossible. I have a 2016 MacBook Pro that works fine, but my new M1 MacBook Pro has issues and restarts, so the incompatibility begins somewhere in that range.

Thanks again for your help!

**Comment by cyrus-and** [comment]
> Is this something that could be integrated into this project - simply a flag that would make the script terminate once a handshake is captured?

I guess it could, let me see... It might not always make sense though, say we explicitly specify multiple targets via `-b`/`-B` or `-s`/`-S`. Then zizzania would quit as soon as the first handshake is captured, regardless of the filters. Not really a problem I guess, thinking out loud here...

> However, I can't get the answers seen here working with zizzania properly which is a bit of an issue.

Hm, there shouldn't be anything particular on that regard about zizzania.

> I have a 2016 MacBook Pro that works fine

Yep, but aren't the captured packets corrupted in you case?

**Comment by Tommrodrigues** [comment]
Hey, thanks for getting back to me again!

That's a good point I hadn't thought of regarding how to handle when to quit for multiple targets. However, I do still think that for some use cases (mine included), having zizzania quit after one or `x` number of full handshakes are captured would be a really useful feature as it allows integrations into other scripts

> Hm, there shouldn't be anything particular on that regard about zizzania.

Yes, you are right. I managed to get it working as you can see [here](https://github.com/Tommrodrigues/WiFiCrackPy/blob/6ea1f29db7257ea96a6021f19ae18a2e9c9a3af3/WiFiCrackPy.py#L63). I was having problems because I assumed the output of zizzania would be treated as `stdout`,  but it was `stderr` instead :) Again, it'd be really helpful and definitely much cleaner if I could simply add a flag that would terminate the script at the point where `Full handshake captured` is announced - if it'd be too difficult to integrate then don't worry as I've been able to find a way around it for now :)

> Yep, but aren't the captured packets corrupted in you case?

Strangely, no. My 2016 15" MacBook Pro seems to capture packets just fine and can even send deauthentication frames no problem... unlike my M1 MacBook Pro. Hopefully someone will work out a way to restore this functionality for newer machines, but in the meantime, I've just been warning people to check their compatibility before trying to send deauth frames etc.

**Comment by cyrus-and** [comment]
Only tested briefly, please give the `-q` option a try.

**Comment by Tommrodrigues** [comment]
That works great, thanks so much for all your help!
