### ISSUE TITLE
[!]Libpcap: That device doesn't support monitor mode

### ISSUE THREAD

**Issue by 95bes1488** [cyrus-and/zizzania#11]
I get this error with all my wifi adapters that exactly support monitor mode, all the dependencies are there, I don't understand what the problem is, please help

**Comment by cyrus-and** [comment]
It's hard to tell without any further information. Can you give me details about your OS and Wi-Fi adapters? Also how are you running zizzania?

Anyway, that error comes from libpcap directly. What does the following command says?

```
sudo tcpdump -i wlan1 --monitor-mode
```

Replace `wlan1` with your adapter.

**Comment by 95bes1488** [comment]
i work with the latest release of kali linux, and i have rt5370 and tp-link 722 v.1. I try tcpdump -i --monitor-mode and i get "tcpdump: wlan1: That device doesn't support monitor mode". But via airmon-ng i can use my adapters in monitore mode

**Comment by cyrus-and** [comment]
I've never used `airmon-ng` (what's the use though?) so I'm not 100% sure, but shouldn't you use the newly created virtual interface, e.g., `wlan1mon`? The one created by running, say, `sudo airmon-ng start wlan1`.

**Comment by 95bes1488** [comment]
also i try it, wlan1mon isn't work too, i get same error. It's very strange so I reached out to you directly as the script creator

**Comment by cyrus-and** [comment]
The built-in adapter of my Raspberry doesn't support monitor mode as it is (I think you need a patched firmware). I usually plug a Wi-Fi dongle in it and use Zizzania without any problems, specifically this one:

```
Ralink Technology, Corp. RT2501/RT2573 Wireless Adapter
```

> But via airmon-ng i can use my adapters in monitore mode

How are you using your adapters when you put them in monitor mode using `airmon-ng`? Say for example you want to use `tcpdump` with them

**Comment by 95bes1488** [comment]
in fact, the rpi built-in adapter can be started in monitor mode, with this command : iw phy phy0 interface add mon0 type monitor
, but I don’t use it, I already wrote which adapters I have, rt5370 and TP-link 722 v.1. When I put my adapters in monitor mode using airmon-ng, the virtual interface gets a name for example wlan1mon, this is the name I usually use. I have never actually used tysipidamp before. i feel so stupid because probably i lost something very simple

**Comment by cyrus-and** [comment]
> i feel so stupid because probably i lost something very simple

Please don't. :)

You can try to force zizzania to not explicitly enter monitor mode:

1. comment out his line:

    https://github.com/cyrus-and/zizzania/blob/ccf3c69f2f14704d070fd5eaef1ed868ef9fd72f/src/handler.c#L48

2. recompile with `make`;

3. put your adapter in monitor mode using `airmon-ng`;

4. use newly created `*mon` interface with zizzania.

**Comment by 95bes1488** [comment]
It worked! thank you very much! you are cool!

**Comment by cyrus-and** [comment]
Awesome! I plan to add an option for that. Can you also please test if that method works passing the `-c` option? Also, how do you usually switch channels in your setup with `airmon-ng`?

**Comment by cyrus-and** [comment]
OK now you can just run zizzania with `-M`:

```
    -M            Do not set <devidce> in RFMON mode (useful for airmon-ng)
```

Thanks for bringing up this issue.

**Comment by 95bes1488** [comment]
> Потрясающий! Я планирую добавить для этого возможность. Не могли бы вы также проверить, работает ли этот метод, передав эту `-c`опцию? Кроме того, как вы обычно переключаете каналы в своей установке `airmon-ng`?

I had to write a simple script that runs Zizzania and AiroDump-ng in parallel. it would be great if you added the ability to automatically switch channels with the ability to adjust the switching time, then this would be the best program for "walk-n-catch"!

**Comment by 95bes1488** [comment]
> Хорошо, теперь вы можете просто запустить zizzania с помощью `-M`:
> 
> ```
>     -M            Do not set <devidce> in RFMON mode (useful for airmon-ng)
> ```
> 
> Спасибо, что подняли этот вопрос.

that is great!

**Comment by cyrus-and** [comment]
> it would be great if you added the ability to automatically switch channels with the ability to adjust the switching time, then this would be the best program for "walk-n-catch"!

Yeah I thought about it multiple times, but I'm afraid of embarking in something too complex to be implemented properly for every use case. I've implemented a script similar to the one you're mentioning and I simply run zizzania for a certain amount of time on a certain channel, then I kill it, switch channel, repeat... It works pretty well, so I don't feel the urge of implementing such feature. But yeah, it might be a good idea...

**Comment by CORDYZEPS** [comment]
Hi! Doesn't work some manipulation with handler.c with me, in what place problem is can be?

**Comment by Pjkjnjd** [comment]
добрый день Sh7yk
вот по этому вопросу
[!]Libpcap: That device doesn't support monitor mode
вы бы могли пояснить
как вы устранили проблему
https://github.com/cyrus-and/zizzania/issues/11#issue-1076706236
может быть сбросите исправленную Вами - zizzania
сюда
[pjkjnjd0@gmail.com](mailto:pjkjnjd0@gmail.com)
спасибо
.....
good afternoon  Sh7yk
here on this issue
[!]Libpcap: That device doesn't support monitor mode
could you explain
how you fixed the problem
https://github.com/cyrus-and/zizzania/issues/11#issue-1076706236
maybe reset the one you fixed - zizzania
this way
[pjkjnjd0@gmail.com](mailto:pjkjnjd0@gmail.com)
thanks
