### ISSUE TITLE
De-auth does not really de-auth

### ISSUE THREAD

**Issue by mtnrabi** [cyrus-and/zizzania#14]
Hi there! 

I'm using the project on mac (ventura).

When running `sudo zizzania -v -i en0 -b <BSSID> -w out.cap` 
(BSSID being my own network access point BSSID which I'm connected to with my phone)
I'm getting this output:
```
[*] Deauthenticating <DEVICE BSSID> @ <ACCESS POINT BSSID>
[*] Deauthenticating <DEVICE BSSID> @ <ACCESS POINT BSSID>
[*] Deauthenticating <DEVICE BSSID> @ <ACCESS POINT BSSID>
[*] Deauthenticating <DEVICE BSSID> @ <ACCESS POINT BSSID>
[*] Deauthenticating <DEVICE BSSID> @ <ACCESS POINT BSSID>
[*] Deauthenticating <DEVICE BSSID> @ <ACCESS POINT BSSID>
...
[*] Giving up with 60:3D:26:DB:37:3A @ 0C:80:63:4B:40:16
```

When re-entering the network on my own it picks the handshake, but the force deauthentication doesn't work...
Am I doing something wrong?

**Comment by cyrus-and** [comment]
It could be that your NIC is not capable of injection, which is often the case with Apple hardware.

**Comment by mtnrabi** [comment]
@cyrus-and Got it, thanks for the quick answer. 
I'll see if I can get an external card that supports it (if you happen to know a cheap one that's compatible with the mac, that would be helpful).

BTW - awesome repo :)

**Comment by cyrus-and** [comment]
Thanks! :)

I don't know, I usually run zizzania on Linux. On macOS I only had luck with some external card in a Linux VM, thus I think whatever works, since it bypasses macOS entirely.
