### ISSUE TITLE
consider creating a git release tag

### ISSUE THREAD

**Issue by anthraxx** [cyrus-and/zizzania#2]
Hey :smile: 

I would like to ask if you could consider to create a git release tag to make packaging easier.
It would also be great if you could remember in the future to (sometimes) create a new release tag :yum: 

cheers

**Comment by cyrus-and** [comment]
Thanks for the suggestion. I didn't consider this because of the very early stage of development and lack of proper testing.

Here's the first release: [v0.0.1](/cyrus-and/zizzania/releases/tag/v0.0.1)

**Comment by anthraxx** [comment]
@cyrus-and awesome, thank you very much :+1:
