### ISSUE TITLE
Feature request:  Add pattern matching for BSSIDs

### ISSUE THREAD

**Issue by mlinton** [cyrus-and/zizzania#4]
So this tool seems great but there are many cases where there are multiple APs with similar BSSIDs, and matching on a portion of the BSSID would be a great feature:

AA:BB:CC:DD:EE:FF
AA:BB:CC:CC:EE:AA

The using a pattern of EE:EE:EE:FF:FF:FF where F is the mask would match both BSSIDs

Then the tool can dynamically add new target AP/Client that match the pattern.  This is similar to how Kismet does this using the filter-match.

Cheers.

Mark

**Comment by cyrus-and** [comment]
This would be a nice feature indeed!
I'll think about it, thank you.

**Comment by cyrus-and** [comment]
Well, better late than never I guess...
