### ISSUE TITLE
error occurs when make install

### ISSUE THREAD

**Issue by xellosiris** [cyrus-and/zizzania#5]
it appears error message below:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 45: ordinal not in range(128):
  File "/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons/Script/Main.py", line 1361:
    _exec_main(parser, values)
  File "/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons/Script/Main.py", line 1324:
    _main(parser)
  File "/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons/Script/Main.py", line 892:
    display("scons: Entering directory `%s'" % script_dir)
  File "/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons/Util.py", line 220:
    sys.stdout.write(UnicodeType(text))
make: *** [release] Error 2

how can I solve this error?

**Comment by cyrus-and** [comment]
This seems a problem with SCons, you should file this issue [here][1].

But probably running `scons` with the `-s` option may be a quick workaround; just replace `scons` with `scons -s` in the [`Makefile`][2] and try again.

[1]: http://scons.tigris.org/bug-submission.html
[2]: https://github.com/cyrus-and/zizzania/blob/master/Makefile

**Comment by xellosiris** [comment]
Thank you very much,appreciate your hard working.

冠為

**Comment by xellosiris** [comment]
Sorry It seems I misunderstand the way how to install zizzania.

I want to install zizzania by following the steps on GitHub.

When I tried to execute [make]

The error message display

File "/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons/Script/Main.py", line 924, in _main
make: *** [release] Error 2

I have tried to running scans with -s but it didn’t` work.

Do you have any idea about this? 

Sorry I’m just a rookie in programming.

**Comment by xellosiris** [comment]
BTW my system is Mac osX.

**Comment by cyrus-and** [comment]
I have the same version of SCons on macOS and everything seems to work fine:

```console
$ make
scons -C src/
scons: Entering directory `/Users/andrea/Dropbox/backup/dev/zizzania/src'
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o bsss.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os bsss.c
gcc -o clients.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os clients.c
gcc -o dispatcher.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os dispatcher.c
gcc -o dissector.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os dissector.c
gcc -o handler.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os handler.c
gcc -o handshake.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os handshake.c
gcc -o ieee802.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os ieee802.c
gcc -o iface.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os iface.c
gcc -o killer.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os killer.c
gcc -o main.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os main.c
gcc -o members.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os members.c
gcc -o options.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os options.c
gcc -o terminal.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os terminal.c
gcc -o util.o -c -std=gnu99 -Wall -I ../deps/uthash -O3 -Os util.c
gcc -o zizzania bsss.o clients.o dispatcher.o dissector.o handler.o handshake.o ieee802.o iface.o killer.o main.o members.o options.o terminal.o util.o -lpthread -lpcap
scons: done building targets.
$ make install
install src/zizzania /usr/local/bin/
```

What's the output of `scons -v`?

```console
$ scons -v
SCons by Steven Knight et al.:
	script: v3.0.0.rel_3.0.0:4395:8972f6a2f699, 2017/09/18 12:59:24, by bdbaddog on ubuntu-16
	engine: v3.0.0.rel_3.0.0:4395:8972f6a2f699, 2017/09/18 12:59:24, by bdbaddog on ubuntu-16
	engine path: ['/usr/local/Cellar/scons/3.0.0_1/libexec/scons-local/SCons']
Copyright (c) 2001 - 2017 The SCons Foundation
```

**Comment by xellosiris** [comment]
I figure out!
 Because of my floder`s name is Chinese


Thank a lot

冠維

**Comment by xellosiris** [comment]
When I start to use zizzania,it seems couldn’t recognize the device (I used en1 WiFi as a interface )does that means it could work on my Mac(10.13.1)?

冠為

**Comment by xellosiris** [comment]
The error message is

wrong device type/mode 'en10mb'; 'ieee802_11_radio' expected

冠為

**Comment by cyrus-and** [comment]
> I figure out! Because of my floder`s name is Chinese

Good find! You should definitely file a bug to SCons.

> wrong device type/mode 'en10mb'; 'ieee802_11_radio' expected

Zizzania doesn't fully support macOS (see [here][1]), it can only read and process packets from file, meaning that you can dump traffic with `airport`, Wireshark or the Apple Wireless Diagnostics application then pass the pcap to Zizzania.

An alternative (if you really want to use macOS) is to spin a Linux virtual machine and use an external USB Wi-Fi adapter.

[1]: https://github.com/cyrus-and/zizzania#mac-os-x-support

**Comment by xellosiris** [comment]
I see.thank you for your reply.
I wondering that if I have a USB wifi adapter which supports RFMON mode, will it available on macOS with zizzania in dump pcap or even sniff pack live?

What I know is airdump and airreply is not fully supports macOS because the programs designed for Linux originally not macOS.Is zizzania has same problem?

**Comment by cyrus-and** [comment]
> you can dump traffic with `airport`, Wireshark or the Apple Wireless Diagnostics application then pass the pcap to Zizzania.

You can do this even with the native Apple adapter (which supports RFMON mode) but if you want to sniff *live* you'll need a Linux VM.

> What I know is airdump and airreply is not fully supports macOS because the programs designed for Linux originally not macOS.Is zizzania has same problem?

I'm not fully aware of why the aircrack-ng suite doesn't support macOS but I guess the same limitations apply, AFAIK vanilla macOS doesn't allow packet injection (with whatever adapter) but only RFMON sniffing and since packet injection is pretty important for Zizzania I didn't bother to implement that (which I may decide to try in the future though).

---

FYI spinning a Linux VM is pretty straightforward with [Vagrant][1].

[1]: https://www.vagrantup.com/intro/getting-started/index.html
