### ISSUE TITLE
Made my computer automatically-shutdown

### ISSUE THREAD

**Issue by caryyu** [cyrus-and/zizzania#9]
Have no idea why this command would've shut my mac computer down after the following execution on Mac OS Catalina:

```
sudo airport -z 
sudo airport --channel=4
sudo zizzania -i en0 -b AA:BB:CC -w output.pcap
```

the symptom was like running the final command for several minutes and then suddenly the monitor display was getting into the darkness, I had to turn it on again with the power button

**Comment by cyrus-and** [comment]
Take a look at #6, do you have the same model of the OP?

**Comment by caryyu** [comment]
This is my Wi-FI information with `MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)`:

```shell
Software Versions:
  CoreWLAN:	13.0 ((null))
  CoreWLANKit:	13.0 ((null))
  Menu Extra:	13.0 ((null))
  System Information:	12.0 (1500)
  IO80211 Family:	12.0 (1200.12.2b1)
  Diagnostics:	1.0 (910)
  AirPort Utility:	Not Installed
  Interfaces:
en0:
  Card Type:	AirPort Extreme  (0x14E4, 0x7BF)
  Firmware Version:	wl0: Feb 28 2020 15:24:56 version 9.30.357.35.32.5.47 FWID 01-9ce4adf3
  MAC Address: REDACTED
  Locale:	RoW
  Country Code:	X2
  Supported PHY Modes:	802.11 a/b/g/n/ac
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165
  Wake On Wireless:	Supported
  AirDrop:	Supported
  AirDrop Channel:	0
  Auto Unlock:	Supported
  Status:	Connected
```

Hope it can make any clue to you, thanks.

**Comment by cyrus-and** [comment]
> Card Type:	AirPort Extreme  (0x14E4, 0x7BF)

You seem to have the same card of the OP at #6.

I just know that some MacBooks have issues with that, specifically for what concerns the injection (the likely cause of the crash?). I guess there's nothing I can do on my side, but what you can do is to try passive mode (`-n`) or use an USB dongle with a Linux VM.

Keep in mind though that even when it doesn't crash, the information gathered from a NIC in monitor mode on macOS is not reliable. (See #6.)
